<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://memorynotfound.com/beer"
    targetNamespace="http://memorynotfound.com/beer">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            attributeFormDefault="unqualified" 
            elementFormDefault="qualified">
            <xs:import
                namespace="http://memorynotfound.com/beer"
                schemaLocation="../xsd/beer.xsd"></xs:import>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="BeerResponse">
        <wsdl:part 
            element="tns:BeerResponse" 
            name="BeerResponse">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="BeerRequest">
        <wsdl:part 
            element="tns:BeerRequest" 
            name="BeerRequest">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="BeerService">
        <wsdl:operation name="getBeer">
            <wsdl:input  message="tns:BeerRequest" name="BeerRequest">
            </wsdl:input>
            <wsdl:output  message="tns:BeerResponse" name="BeerResponse">
            </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding 
        name="BeerServiceSoap11" 
        type="tns:BeerService">
        <soap:binding 
            style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="getBeer">
            <soap:operation soapAction="" />
            <wsdl:input name="BeerRequest">
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output name="BeerResponse">
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="BeerService">
        <wsdl:port 
            binding="tns:BeerServiceSoap11" 
            name="BeerServiceSoap11">
            <soap:address 
                location="http://localhost:8080/ws/beerservice" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>